SELECT
    DBMS_UTILITY.GET_HASH_VALUE(LISTAGG(TEXT, '') WITHIN GROUP (ORDER BY LINE), 100000000, 1) AS HASH_PROC1
FROM ALL_SOURCE WHERE NAME = 'PROCEDURE_1' AND TYPE = 'PROCEDURE';

SELECT
    DBMS_UTILITY.GET_HASH_VALUE(LISTAGG(TEXT, '') WITHIN GROUP (ORDER BY LINE), 100000000, 1) AS HASH_PROC2
FROM ALL_SOURCE WHERE NAME = 'PROCEDURE_2' AND TYPE = 'PROCEDURE';

--verifica se os códigos são diferentes sem listar mudanças