SELECT LINE, TEXT FROM ALL_SOURCE
WHERE NAME = 'PROCEDURE_1' AND TYPE = 'PROCEDURE'
MINUS
SELECT LINE, TEXT FROM ALL_SOURCE
WHERE NAME = 'PROCEDURE_2' AND TYPE = 'PROCEDURE';

--comparar linha por linha
